version: '3.1'
services:
  jenkins:
    image: 256cb12e72d6
    container_name: jenkins
    user: root
    environment:
      JENKINS_HOST_HOME: "/opt/jenkins/data/jenkins"
      - DOCKER_HOST=tcp://host.docker.internal:2375
       networks:
            - frontend

    ports:
      - "9080:8080"
      - "5005:5000"
      - "50005:50000"
  nexus:
    image: sonatype/nexus3:3.16.2
    ports:
      - "9081:8081"
networks:
    frontend: null
    backend: null
volumes:
    db-data: null
