version: '3.1'
services:
  jenkins:
    image: istresearch/jenkins:latest
    container_name: jenkins
    user: jenkins
    environment:
      JENKINS_HOST_HOME: "/opt/jenkins/data/jenkins"
    ports:
      - "9080:8080"
      - "5005:5000"
      - "50005:50000"

  nexus:
    image: sonatype/nexus3:3.16.2
    ports:
      - "9081:8081"
